# Generated by Django 4.0.4 on 2022-06-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_neighbourhood_amenities_hood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='details',
            field=models.TextField(max_length=20),
        ),
    ]
