# Generated by Django 4.0.4 on 2022-06-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_announcements_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='details',
            field=models.TextField(),
        ),
    ]
